import fs from "fs";
const plugins = `alefragnani.project-manager
amatiasq.sort-imports
be5invis.toml
CodeInChinese.EnglishChineseDictionary
cschlosser.doxdocgen
cssho.vscode-svgviewer
dbaeumer.vscode-eslint
donjayamanne.githistory
eamodio.gitlens
formulahendry.code-runner
jawandarajbir.react-vscode-extension-pack
jeff-hykin.better-cpp-syntax
jock.svg
johnsoncodehk.volar
MaxvanderSchee.web-accessibility
mhutchie.git-graph
ms-dotnettools.csharp
ms-python.python
ms-python.vscode-pylance
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.remote-wsl
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
ms-vscode.powershell
msjsdiag.debugger-for-chrome
msjsdiag.debugger-for-edge
rust-lang.rust
rvest.vs-code-prettier-eslint
streetsidesoftware.code-spell-checker
svipas.prettier-plus
twxs.cmake
wix.vscode-import-cost
yzhang.markdown-all-in-one
bungcip.better-toml
cheshirekow.cmake-format
codezombiech.gitignore
donjayamanne.git-extension-pack
donjayamanne.python-extension-pack
dunstontc.vscode-rust-syntax
dustypomerleau.rust-syntax
evgeniypeshkov.syntax-highlighter
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
foxundermoon.shell-format
Gruntfuggly.todo-tree
JScearcy.rust-doc-viewer
kisstkondoros.vscode-gutter-preview
lorenzopirro.rust-flash-snippets
magicstack.MagicPython
matklad.rust-analyzer
mike-co.import-sorter
mikestead.dotenv
miqh.vscode-language-rust
mooman219.rust-assist
ms-azuretools.vscode-docker
ms-vscode-remote.vscode-remote-extensionpack
nyxiative.rust-and-friends
Orta.vscode-jest
PolyMeilex.rust-targets
ritwickdey.LiveServer
serayuzgur.crates
Shan.code-settings-sync
statiolake.vscode-rustfmt
steoates.autoimport
stevencl.addDocComments
Swellaby.rust-pack
TabNine.tabnine-vscode
tamasfe.even-better-toml
techer.open-in-browser
tht13.python
usernamehw.errorlens
vadimcn.vscode-lldb
VisualStudioExptTeam.vscodeintellicode
vscode-icons-team.vscode-icons
wayou.vscode-todo-highlight
xaver.clang-format
ZhangYue.rust-mod-generator
ziyasal.vscode-open-in-github
alefragnani.project-manager
austin.code-gnu-global
bungcip.better-toml
cheshirekow.cmake-format
christian-kohler.path-intellisense
codezombiech.gitignore
CoenraadS.bracket-pair-colorizer-2
cschlosser.doxdocgen
donjayamanne.git-extension-pack
donjayamanne.githistory
dustypomerleau.rust-syntax
eamodio.gitlens
esbenp.prettier-vscode
evgeniypeshkov.syntax-highlighter
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
formulahendry.code-runner
foxundermoon.shell-format
GitHub.copilot
jeff-hykin.better-cpp-syntax
johnsoncodehk.volar
johnsoncodehk.vscode-typescript-vue-plugin
JScearcy.rust-doc-viewer
lorenzopirro.rust-flash-snippets
matklad.rust-analyzer
mhutchie.git-graph
mikestead.dotenv
MisterJ.vue-volar-extention-pack
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.remote-wsl
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
ms-vscode.vscode-typescript-tslint-plugin
nyxiative.rust-and-friends
PolyMeilex.rust-targets
rust-lang.rust
serayuzgur.crates
sibiraj-s.vscode-scss-formatter
statiolake.vscode-rustfmt
steoates.autoimport
streetsidesoftware.code-spell-checker
svipas.prettier-plus
Swellaby.rust-pack
syler.sass-indented
TabNine.tabnine-vscode
tamasfe.even-better-toml
twxs.cmake
vadimcn.vscode-lldb
wix.vscode-import-cost
Wscats.vue
xabikos.JavaScriptSnippets
xaver.clang-format
yzhang.markdown-all-in-one
ZhangYue.rust-mod-generator
ziyasal.vscode-open-in-github
2gua.rainbow-brackets
abusaidm.html-snippets
adpyke.codesnap
alefragnani.project-manager
austin.code-gnu-global
bungcip.better-toml
cheshirekow.cmake-format
christian-kohler.path-intellisense
CodeInChinese.EnglishChineseDictionary
codezombiech.gitignore
CoenraadS.bracket-pair-colorizer
CoenraadS.bracket-pair-colorizer-2
cschlosser.doxdocgen
cssho.vscode-svgviewer
dbaeumer.vscode-eslint
donjayamanne.git-extension-pack
donjayamanne.githistory
donjayamanne.python-environment-manager
donjayamanne.python-extension-pack
dunstontc.vscode-rust-syntax
dustypomerleau.rust-syntax
eamodio.gitlens
ecmel.vscode-html-css
EditorConfig.EditorConfig
eg2.vscode-npm-script
esbenp.prettier-vscode
evan-buss.font-switcher
evgeniypeshkov.syntax-highlighter
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
formulahendry.code-runner
foxundermoon.shell-format
GitHub.copilot
Gruntfuggly.todo-tree
hollowtree.vue-snippets
jeff-hykin.better-cpp-syntax
jock.svg
johnsoncodehk.volar
johnsoncodehk.vscode-typescript-vue-plugin
JScearcy.rust-doc-viewer
KevinRose.vsc-python-indent
kisstkondoros.vscode-gutter-preview
lorenzopirro.rust-flash-snippets
magicstack.MagicPython
matklad.rust-analyzer
mhutchie.git-graph
mike-co.import-sorter
mikestead.dotenv
miqh.vscode-language-rust
MisterJ.vue-volar-extention-pack
mooman219.rust-assist
ms-azuretools.vscode-docker
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.remote-wsl
ms-vscode-remote.vscode-remote-extensionpack
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
ms-vscode.powershell
ms-vscode.vscode-typescript-tslint-plugin
njpwerner.autodocstring
nyxiative.rust-and-friends
Orta.vscode-jest
PolyMeilex.rust-targets
ritwickdey.LiveServer
rust-lang.rust
serayuzgur.crates
Shan.code-settings-sync
sibiraj-s.vscode-scss-formatter
statiolake.vscode-rustfmt
steoates.autoimport
stevencl.addDocComments
streetsidesoftware.code-spell-checker
svipas.prettier-plus
Swellaby.rust-pack
syler.sass-indented
TabNine.tabnine-vscode
tamasfe.even-better-toml
techer.open-in-browser
tht13.python
twxs.cmake
usernamehw.errorlens
vadimcn.vscode-lldb
VisualStudioExptTeam.vscodeintellicode
vscode-icons-team.vscode-icons
wayou.vscode-todo-highlight
wholroyd.jinja
wix.vscode-import-cost
Wscats.vue
xabikos.JavaScriptSnippets
xabikos.ReactSnippets
xaver.clang-format
yzhang.markdown-all-in-one
ZhangYue.rust-mod-generator
ziyasal.vscode-open-in-github`;

const list = plugins
  .split("\n")
  .filter((i) => i.length)
  .map((i) => i.trim());
const s = new Set(list);
const str = JSON.stringify([...s]);
fs.writeFileSync("./ubuntu/plugin.json", str);
console.log(s.size);
